import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  methodik: [{type: 'autogenerated', dirName: 'methodik'}],
  technik: [{type: 'autogenerated', dirName: 'technik'}],
};

export default sidebars;
